AWSTemplateFormatVersion: 2010-09-09
Description: |
  Kittens Carousel is a static website application deployed 
  with Apache Web Server on AWS Elastic Compute Cloud (EC2) 
  Instance using AWS Cloudformation Service. 
Resources:
  OzgurCFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups:
        - cfn-sec-group
      Tags:
        - Key: Name 
          Value: Web server of Kittens Carousel static website 
      UserData: 
        Fn::Base64:
          !SUb |
                    Fn::Base64:
          !Sub |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            FOLDER=https://raw.githubusercontent.com/ozgurgula/my-projects/main/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web
            cd /var/www/html
            wget $FOLDER/index.html
            wget $FOLDER/cat0.jpg
            wget $FOLDER/cat1.jpg
            wget $FOLDER/cat2.jpg
            wget $FOLDER/cat3.png
            systemctl start httpd
            systemctl enable httpd    
Outputs:
  websiteUrl:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt  WebServerHost.PublicDnsName
    Description: Kittens Carousel Application URL        